#!/usr/bin/env bash
# scripts/dev.sh — Start the full local development stack
#
# What this does:
#   1. Checks prerequisites (Supabase CLI, Docker)
#   2. Creates supabase/functions -> edge-functions symlink so the CLI can find them
#   3. Starts the Supabase local emulator (Postgres, Auth, Storage, Studio, Edge Runtime)
#   4. Prints the local URLs and injects them into a .env.local for the frontend
#
# Usage: bash scripts/dev.sh
# Stop:  supabase stop

set -euo pipefail

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo -e "${CYAN}=== SellingDubai Local Dev Stack ===${NC}"
echo ""

# ── Prerequisites ──────────────────────────────────────────────────────────────
if ! command -v supabase &>/dev/null; then
  echo -e "${RED}ERROR: Supabase CLI not found.${NC}"
  echo "  Install: brew install supabase/tap/supabase"
  exit 1
fi

if ! docker info &>/dev/null 2>&1; then
  echo -e "${RED}ERROR: Docker is not running.${NC}"
  echo "  Start Docker Desktop and try again."
  exit 1
fi

# ── Symlink edge-functions/ into supabase/functions/ ──────────────────────────
# The Supabase CLI expects functions at supabase/functions/<name>/index.ts
# Our functions live at edge-functions/<name>/index.ts
# This symlink bridges the gap without moving files.
FUNCTIONS_LINK="$ROOT/supabase/functions"
if [ ! -e "$FUNCTIONS_LINK" ]; then
  ln -s "$ROOT/edge-functions" "$FUNCTIONS_LINK"
  echo -e "${GREEN}Created${NC} supabase/functions -> edge-functions (symlink)"
elif [ -L "$FUNCTIONS_LINK" ]; then
  echo -e "${GREEN}OK${NC}     supabase/functions symlink already exists"
else
  echo -e "${YELLOW}WARN${NC}   supabase/functions exists as a real directory — remove it and re-run if functions don't serve"
fi

# ── Secrets file ──────────────────────────────────────────────────────────────
SECRETS_FILE="$ROOT/supabase/.env"
if [ ! -f "$SECRETS_FILE" ]; then
  echo -e "${YELLOW}WARN${NC}   supabase/.env not found — copying from supabase/.env.example"
  cp "$ROOT/supabase/.env.example" "$SECRETS_FILE"
  echo "       Edit supabase/.env with your local secrets before functions will work fully."
fi

# ── Prod guard ────────────────────────────────────────────────────────────────
# Abort if supabase/.env still points at the production database.
PROD_URL="https://pjyorgedaxevxophpfib.supabase.co"
if grep -q "SUPABASE_URL=${PROD_URL}" "$SECRETS_FILE" 2>/dev/null; then
  echo ""
  echo -e "${RED}BLOCKED: supabase/.env has SUPABASE_URL set to the PRODUCTION URL.${NC}"
  echo "  Local development must target http://127.0.0.1:54321."
  echo "  The correct URL is filled automatically by 'supabase start' via the edge runtime."
  echo "  Remove the SUPABASE_URL line from supabase/.env and try again."
  exit 1
fi

# ── Start emulator ────────────────────────────────────────────────────────────
echo ""
echo "Starting Supabase local stack (first run pulls Docker images — may take a few minutes)..."
supabase start

# ── Print status and build .env.local for frontend ────────────────────────────
STATUS=$(supabase status 2>/dev/null)
LOCAL_URL=$(echo "$STATUS" | grep "API URL" | awk '{print $NF}')
LOCAL_ANON=$(echo "$STATUS" | grep "anon key" | awk '{print $NF}')
STUDIO_URL=$(echo "$STATUS" | grep "Studio URL" | awk '{print $NF}')
INBUCKET_URL=$(echo "$STATUS" | grep "Inbucket URL" | awk '{print $NF}')

# Write .env.local so the frontend JS can optionally read local config
# (Currently the frontend hardcodes prod — this enables future parameterisation)
cat > "$ROOT/.env.local" <<EOF
# Auto-generated by scripts/dev.sh — DO NOT COMMIT
# These are your LOCAL Supabase credentials (safe — they're not your prod keys)
SUPABASE_LOCAL_URL=${LOCAL_URL:-http://127.0.0.1:54321}
SUPABASE_LOCAL_ANON_KEY=${LOCAL_ANON:-}
EOF

echo ""
echo -e "${GREEN}=== Local stack is running ===${NC}"
echo ""
echo -e "  Supabase API:   ${CYAN}${LOCAL_URL:-http://127.0.0.1:54321}${NC}"
echo -e "  Studio:         ${CYAN}${STUDIO_URL:-http://127.0.0.1:54323}${NC}"
echo -e "  Email inbox:    ${CYAN}${INBUCKET_URL:-http://127.0.0.1:54324}${NC}  ← all magic links land here"
echo -e "  Postgres:       ${CYAN}postgresql://postgres:postgres@127.0.0.1:54322/postgres${NC}"
echo ""
echo "Next: open a second terminal and run:"
echo -e "  ${CYAN}supabase functions serve --env-file ./supabase/.env --no-verify-jwt${NC}"
echo "  (--no-verify-jwt disables JWT auth locally so you can call functions without a token)"
echo ""
echo "To serve a SINGLE function:"
echo -e "  ${CYAN}supabase functions serve capture-lead-v4 --env-file ./supabase/.env --no-verify-jwt${NC}"
echo ""
echo "To stop everything: supabase stop"
